### ISSUE TITLE
working with Scrapy

### ISSUE THREAD

**Issue by JamCh01** [monkey-soft/Scrapy_IPProxyPool#2]
Hello, I have rewritten your project. But there were some problems about working with Scrapy. So is there any way to connect with you?

**Comment by monkey-soft** [comment]
> Hello, I have rewritten your project. But there were some problems about working with Scrapy. So is there any way to connect with you?

You can connect me with E-mail.

**Comment by JamCh01** [comment]
> > Hello, I have rewritten your project. But there were some problems about working with Scrapy. So is there any way to connect with you?
> 
> You can connect me with E-mail.

Thanks for your reply, I have sent email to you~
